/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HelloWorldInterface extends Interface {
    getFunction(nameOrSignature: "greeting" | "setGreeting"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GreetingChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'greeting', values?: undefined): string;
encodeFunctionData(functionFragment: 'setGreeting', values: [string]): string;

    decodeFunctionResult(functionFragment: 'greeting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGreeting', data: BytesLike): Result;
  }

  
    export namespace GreetingChangedEvent {
      export type InputTuple = [previous: string, next: string, by: AddressLike];
      export type OutputTuple = [previous: string, next: string, by: string];
      export interface OutputObject {previous: string, next: string, by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HelloWorld extends BaseContract {
    
    connect(runner?: ContractRunner | null): HelloWorld;
    waitForDeployment(): Promise<this>;

    interface: HelloWorldInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    greeting: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setGreeting: TypedContractMethod<
      [next: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'greeting'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setGreeting'): TypedContractMethod<
      [next: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'GreetingChanged'): TypedContractEvent<GreetingChangedEvent.InputTuple, GreetingChangedEvent.OutputTuple, GreetingChangedEvent.OutputObject>;

    filters: {
      
      'GreetingChanged(string,string,address)': TypedContractEvent<GreetingChangedEvent.InputTuple, GreetingChangedEvent.OutputTuple, GreetingChangedEvent.OutputObject>;
      GreetingChanged: TypedContractEvent<GreetingChangedEvent.InputTuple, GreetingChangedEvent.OutputTuple, GreetingChangedEvent.OutputObject>;
    
    };
  }