import { getNoteHash } from "@/helpers/functions/get-note-hash.js";
import { getNullifier } from "@/helpers/functions/get-nullifier.js";
import { getSwapDetails, encodeV3Path, encodeV4Route } from "@/helpers/functions/swap.js";
import { getMerkleTree } from "@/helpers/objects/poseidon-merkle-tree.js";
import {
  createInputNote,
  emptyInputNote,
} from "@/helpers/note-formatting.js";
import SwapVerifierModule from "@/ignition/modules/SwapVerifier.js";
import { PoseidonMerkleTree } from "@pampalo/shared/classes/PoseidonMerkleTree";
import { poseidon2Hash } from "@zkpassport/poseidon2";
import { ethers } from "ethers";
import hre from "hardhat";
import { expect } from "chai";
import Poseidon2HuffJson from "../contracts/utils/Poseidon2Huff.json" with { type: "json" };

// Round-trip: a REAL swap proof (generated by the same bb.js the rest of
// the wallet uses) verified on-chain by the generated SwapVerifier,
// against a harness-seeded note whose off-chain tree root matches the
// contract's currentRoot. The swap *leg* runs against a mock venue so
// this needs no forked liquidity — what it proves is the public-input
// layout + on-chain verification + nullify/insert wiring, end-to-end.
// (Forked v4/v3 liquidity tests are a separate, RPC-gated suite.)

type Venue = "v3" | "v4";

const INPUT_AMOUNT = 100_000_000n; // note amount, fully sent to the pool
const OUT_PER_IN_WAD = 5n * 10n ** 17n; // 0.5 out per in
const REALIZED = (INPUT_AMOUNT * OUT_PER_IN_WAD) / 10n ** 18n;
const TARGET_OUTPUT = REALIZED - 10_000_000n;

describe("private swap (round-trip, real verifier)", () => {
  for (const venue of ["v3", "v4"] as Venue[]) {
    it(`${venue}: verifies a real proof on-chain and rejects replay`, async () => {
      const connection = await hre.network.connect();
      const Signers = await connection.ethers.getSigners();

      // Tokens.
      const usdc = (await (
        await connection.ethers.getContractFactory("USDC")
      ).deploy()) as unknown as ethers.Contract;
      await usdc.waitForDeployment();
      const weth = (await (
        await connection.ethers.getContractFactory("MintableERC20")
      ).deploy("Wrapped Ether", "WETH", 18)) as unknown as ethers.Contract;
      await weth.waitForDeployment();

      // Real generated verifier (library-linked) via its ignition module.
      const { swapVerifier } = await connection.ignition.deploy(
        SwapVerifierModule,
      );

      // Mock venue funded with output token.
      let venueAddr: string;
      if (venue === "v3") {
        const router = (await (
          await connection.ethers.getContractFactory("MockV3SwapRouter")
        ).deploy()) as unknown as ethers.Contract;
        await router.waitForDeployment();
        await router.setRate(OUT_PER_IN_WAD);
        venueAddr = await router.getAddress();
      } else {
        const pm = (await (
          await connection.ethers.getContractFactory("MockV4PoolManager")
        ).deploy()) as unknown as ethers.Contract;
        await pm.waitForDeployment();
        await pm.setRate(OUT_PER_IN_WAD);
        venueAddr = await pm.getAddress();
      }
      await weth.mint(venueAddr, REALIZED * 10n);

      const contractName =
        venue === "v3" ? "PampaloSwapV3Harness" : "PampaloSwapV4Harness";
      const z = ethers.ZeroAddress;
      const pampalo = (await (
        await connection.ethers.getContractFactory(contractName)
      ).deploy(
        z,
        z,
        z,
        z,
        venueAddr,
        await swapVerifier.getAddress(),
      )) as unknown as ethers.Contract;
      await pampalo.waitForDeployment();

      // Poseidon hasher + pooled USDC.
      const poseidon = await new ethers.ContractFactory(
        [],
        Poseidon2HuffJson.bytecode,
        Signers[0],
      ).deploy();
      await poseidon.waitForDeployment();
      await pampalo.setPoseidon(await poseidon.getAddress());
      await usdc.mint(await pampalo.getAddress(), INPUT_AMOUNT * 10n);

      // Build the asset-A note and seed it into both trees at index 0.
      const assetA = BigInt(usdc.target as string);
      const assetB = BigInt(weth.target as string);
      const ownerSecret =
        10036677144260647934022413515521823129584317400947571241312859176539726523915n;
      const owner = BigInt(poseidon2Hash([ownerSecret]).toString());
      const noteSecret =
        2389312107716289199307843900794656424062350252250388738019021107824217896920n;

      const leaf = await getNoteHash(owner, noteSecret, assetA, INPUT_AMOUNT);
      await pampalo.harnessInsert(leaf);

      const tree: PoseidonMerkleTree = await getMerkleTree();
      await tree.insert(leaf.toString(), 0);

      // Off-chain root must match the on-chain root after the seed.
      expect((await tree.getRoot()).toString()).to.equal(
        (await pampalo.currentRoot()).toString(),
      );

      const merkleProof = await tree.getProof(0);
      const inputNote = createInputNote(
        assetA,
        INPUT_AMOUNT,
        owner,
        ownerSecret,
        noteSecret,
        0n,
        merkleProof.siblings,
        merkleProof.indices,
      );
      const nullifier = await getNullifier(
        0n,
        owner,
        noteSecret,
        assetA,
        INPUT_AMOUNT,
      );

      // Output B note @ T.
      const bOwnerSecret =
        6955001134965379637962992480442037189090898019061077075663294923529403402038n;
      const bOwner = BigInt(poseidon2Hash([bOwnerSecret]).toString());
      const bSecret =
        3957740128091467064337395812164919758932045173069261808814882570720300029469n;
      const bHash = await getNoteHash(bOwner, bSecret, assetB, TARGET_OUTPUT);

      const { proof } = await getSwapDetails(
        tree,
        [inputNote, emptyInputNote, emptyInputNote],
        [nullifier, 0n, 0n],
        [bHash, 0n, 0n],
        {
          inputAsset: assetA,
          inputAmount: INPUT_AMOUNT,
          outputAsset: assetB,
          targetOutput: TARGET_OUTPUT,
          swapOutputOwner: bOwner,
          swapOutputSecret: bSecret,
          changeAmount: 0n,
          changeOwner: 0n,
          changeSecret: 0n,
        },
      );

      const route =
        venue === "v3"
          ? encodeV3Path([usdc.target as string, weth.target as string], [3000])
          : encodeV4Route([
              {
                key: {
                  currency0: usdc.target as string,
                  currency1: weth.target as string,
                  fee: 3000,
                  tickSpacing: 60,
                  hooks: ethers.ZeroAddress,
                },
                zeroForOne: true,
              },
            ]);

      const usdcBefore = await usdc.balanceOf(await pampalo.getAddress());
      const wethBefore = await weth.balanceOf(await pampalo.getAddress());

      await expect(
        pampalo.privateSwap(proof.proof, proof.publicInputs, route, []),
      ).to.emit(pampalo, "PrivateSwapExecuted");

      expect(await usdc.balanceOf(await pampalo.getAddress())).to.equal(
        usdcBefore - INPUT_AMOUNT,
      );
      expect(await weth.balanceOf(await pampalo.getAddress())).to.equal(
        wethBefore + REALIZED,
      );
      const nullifierHex = "0x" + nullifier.toString(16).padStart(64, "0");
      expect(await pampalo.nullifierUsed(nullifierHex)).to.equal(true);

      // Replay the same proof: root is still known, but the nullifier is
      // now spent.
      await expect(
        pampalo.privateSwap(proof.proof, proof.publicInputs, route, []),
      ).to.be.revertedWith("Nullifier already spent");
    });
  }
});
